Initial full App setup with all routes and core components

Added navigation structure with Hero, Features, Dashboard, Login, Signup, AI Film, Voice, Face Swap, and Download pages. Integrated Navbar and Footer across routes. This sets the foundation for a fully international, mobile-friendly AI film platform.￼Enter
import { BrowserRouter as Router, Routes, Route } from "react-router-dom"; import { Hero, Features, Footer, Navbar } from "./components"; import Dashboard from "./pages/Dashboard"; import Login from "./auth/Login"; import Signup from "./auth/Signup"; import FilmAI from "./features/FilmAI"; import VoiceAI from "./features/VoiceAI"; import FaceSwap from "./features/FaceSwap"; import Download from "./pages/Download";

export default function App() { return ( <Router> <div className="bg-black text-white min-h-screen"> <Navbar /> <Routes> <Route path="/" element={<> <Hero /> <Features /> </>} /> <Route path="/dashboard" element={<Dashboard />} /> <Route path="/ai/film" element={<FilmAI />} /> <Route path="/ai/voice" element={<VoiceAI />} /> <Route path="/ai/faceswap" element={<FaceSwap />} /> <Route path="/download" element={<Download />} /> <Route path="/login" element={<Login />} /> <Route path="/signup" element={<Signup />} /> </Routes> <Footer /> </div> </Router> ); }

import { BrowserRouter as Router, Routes, Route } from "react-router-dom"; import Navbar from "./components/Navbar"; import Hero from "./components/Hero"; import Features from "./components/Features"; import Footer from "./components/Footer"; import Dashboard from "./pages/Dashboard"; import Login from "./auth/Login"; import Signup from "./auth/Signup"; import FilmAI from "./features/FilmAI"; import VoiceAI from "./features/VoiceAI"; import FaceSwap from "./features/FaceSwap"; import Download from "./pages/Download";

export default function App() { return ( <Router> <div className="bg-black text-white min-h-screen"> <Navbar /> <Routes> <Route path="/" element={<> <Hero /> <Features /> </>} /> <Route path="/dashboard" element={<Dashboard />} /> <Route path="/ai/film" element={<FilmAI />} /> <Route path="/ai/voice" element={<VoiceAI />} /> <Route path="/ai/faceswap" element={<FaceSwap />} /> <Route path="/download" element={<Download />} /> <Route path="/login" element={<Login />} /> <Route path="/signup" element={<Signup />} /> </Routes> <Footer /> </div> </Router> ); }

